"""
Configuration — loads from environment / .env file.

Load order (first wins):
  1. Actual environment variables
  2. .env in current working directory
  3. ~/.config/issuesheriff/.env  (written by `issuesheriff setup`)
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path


USER_CONFIG_DIR = Path.home() / ".config" / "issuesheriff"
USER_CONFIG_FILE = USER_CONFIG_DIR / ".env"


@dataclass
class Config:
    github_token: str = ""
    openai_api_key: str = ""
    openai_model: str = "gpt-4o-mini"
    ollama_model: str = ""
    ollama_base_url: str = "http://localhost:11434"
    similarity_threshold: float = 0.45
    max_issues: int = 100


@lru_cache(maxsize=1)
def get_config() -> Config:
    """
    Load config from environment.
    Respects .env in cwd and ~/.config/issuesheriff/.env as fallback.
    """
    _try_load_dotenv()

    return Config(
        github_token=os.getenv("GITHUB_TOKEN", ""),
        openai_api_key=os.getenv("OPENAI_API_KEY", ""),
        openai_model=os.getenv("ISSUESHERIFF_MODEL", "gpt-4o-mini"),
        ollama_model=os.getenv("OLLAMA_MODEL", ""),
        ollama_base_url=os.getenv("OLLAMA_BASE_URL", "http://localhost:11434"),
        similarity_threshold=float(os.getenv("SIMILARITY_THRESHOLD", "0.45")),
        max_issues=int(os.getenv("MAX_ISSUES", "100")),
    )


def _try_load_dotenv() -> None:
    try:
        from dotenv import load_dotenv
        if USER_CONFIG_FILE.exists():
            load_dotenv(USER_CONFIG_FILE, override=False)
        load_dotenv(override=False)
    except ImportError:
        if USER_CONFIG_FILE.exists():
            _load_env_file_manual(USER_CONFIG_FILE)


def _load_env_file_manual(path: Path) -> None:
    """Minimal .env parser (no python-dotenv fallback)."""
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


def save_user_config(values: dict) -> Path:
    """Write key=value pairs to ~/.config/issuesheriff/.env"""
    USER_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# IssueSheriff user config — generated by `issuesheriff setup`",
        "# Edit manually or re-run `issuesheriff setup` to update.",
        "",
    ]
    for key, value in values.items():
        if value:
            lines.append(f"{key}={value}")
    USER_CONFIG_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return USER_CONFIG_FILE


def load_existing_user_config() -> dict:
    """Read current values from user config for pre-filling the wizard."""
    result = {}
    if not USER_CONFIG_FILE.exists():
        return result
    for line in USER_CONFIG_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        result[key.strip()] = value.strip().strip('"').strip("'")
    return result
